### ISSUE TITLE
Interact via REST API

### ISSUE THREAD

**Issue by pascalchristian** [BogdanMarghescu/YOLOv8-Object-Detection-and-Image-Segmentation#4]
Any ways to do this? Seems that the json result is not exposed via http?

**Comment by OMEGAMAX10** [comment]
Hello! Unfortunately, my application doesn't have a REST API, since it was intended as a web interactive application rather than an API. Furthermore, I don't believe that my app should be an API since it will be very difficult to transmit the detected object masks back to the client (that's because the masks are basically a matrix with the same width and height of the original image, making it too large to be transported).
